image: node:6.14.2

variables:
  GH_REPO_NAME: grig
  GH_REPO_REF: gitlab.com/haxe-grig/grig.git

before_script:
 - npm install -g lix
 - lix download

pages:
  only:
   - master
  script:
   - haxe doc.hxml
   - rm -rf public
   - mkdir public
   - cp -R docs/* public/
   - lix run dox -i bin -o public/api
  artifacts:
    paths:
     - public
