# This will run on Travis' 'new' container-based infrastructure
sudo: required
dist: trusty

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: grig
    - GH_REPO_REF: github.com/osakared/grig.git

language: node_js
node_js: 6

os:
  - linux
  - osx
  
install:
  - npm install -g lix

script:
  - lix download
  - haxe doc.hxml
  - ./generate_documentation.sh